---
kind: pipeline
type: ssh
name: thor_fe
server:
  host:
    from_secret: apps-host
  user:
    from_secret: apps-user
  password:
    from_secret: apps-pwd
steps:
  - name: thor fe deploy
    commands:
      - chmod 755 ./build.sh
      - sh build.sh
trigger:
  branch:
    - master
